PARENTAL_MODULES = []

CONFIG_OPTIONS = {
        'mandatory' : ['exp_type', 'omega', 'l0', 'l1', 'porosity',
                       'inv_init_params', 'wl_out1', 're',
                       'show_figures'],
        'defaults'  : {'rho': 1.0, 'g': 981.,
                       'max_steps': 800, 'max_step_size': 800.},
        'dependent' : {'theta_r':
                       (lambda cfg: len(cfg.get_value('inv_init_params')) == 2,
                        ['theta_r'])},
        'optional'  : [],
        'additional': [],

        # options generated by mkini
        ('measurements_length', -1)]
        }

EXCLUDE_FROM_MODEL = ['measurements_length']

OPTIONS_ITERABLE_LISTS = []

PROVIDE_OPTIONS = []

def check_cfg(cfg):
    return True

def adjust_cfg(cfg):
    pass
