#!/usr/bin/python

from auxiliaryfunctions import CVS2inifiles

csv_file = 'data/computational_data.csv'
out_dir  = 'data'
filename_prefix = 'saturated_heights'


CVS2inifiles(csv_file, out_dir, filename_prefix)
